<?php
/*
************************************************************************************

Model :

Ce fichier ne contiendra que des fonctions. Le modèle a pour but de gérer l'organisation des données. Chacune de ces fonctions
effectuera une action bien précise. Vous ne pourrez effectuer des requêtes SQL que dans ces fonctions ! Le contrôleur et la vue
ne devront contenir aucun appel à MySQL

*******************************************************************************
*/

?>

<?php

$myconnect1= new mysqli("localhost" ,"3wa", "troiswa","library");

function add()
{
    $requete = 'INSERT INTO books (book_title, author_name)
                    VALUES ("' . $_POST["title"].'","' . $_POST["author"].'")';
    $myconnect1->query($requete);
}

function update()
{
    $requeteMAJ =
        'UPDATE books SET       book_title = "'.$_POST["title"].'" ,
                                author_name= "'.$_POST["authorName"].'"
                      WHERE     book_title = "'.$bookTitle.'"
                                AND author_name = "'. $authorName.'"';
    $myconnect1->query($requeteMAJ) ;
}

function modify()
{
    $requete ='SELECT * FROM books WHERE book_id=' .$_GET["bookIndex"];
    $recupsArray = $myconnect1->query($requete) ;
    $lineArray =  $recupsArray->fetch_array() ;
    $bookTitle = $lineArray[1] ;// j'ai besoin que book_title
    $authorName = $lineArray[2] ;// j'ai besoin que author_name
}

function delete()
{
    $requete = 'DELETE FROM books WHERE book_id ='.$_GET['bookIndex'] ;
    $myconnect1->query($requete) ;
}
?>