<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Dragon Slayer</title>
        <link rel="stylesheet" href="//ig-css-reset.googlecode.com/git/reset.css">
        <link rel="stylesheet" href="dragon.css">
    </head>

    <body>
    <section>

        <header><h1> Dragon Slayer of Ivan Is Back ! </h1></header>
        <table class="dragon">
            <th> Dragon     </th>
            <th> Score  </th>
            <th> Weapons </th>
            <tr><td> .<?= $dragonsListe['dragonName'] ?></td>
                <td> .<?= $dragonsListe['dragonLifeMax'] ?></td>
                <td> .<?= $dragonsListe['dragonForce'] ?></td>
            </tr>
        <table>
        <table class="person">
            <th> Person     </th>
            <th> Score  </th>
            <th> Weapons </th>
            <tr><td> .<?= $characterListe['characterName'] ?></td>
                <td> .<?= $characterListe['characterLifeMax'] ?></td>
                <td> .<?= $weaponListe['weaponName'] ?></td>
            </tr>
        <table>


    </section>


    </body>
</html>